export const PRICING_USD = [
  {
    name: "Launch",
    price: "Starting at $499",
    sub: "for small business websites",
    color: "#10B981",
    popular: false,
    features: [
      "Up to 5 Premium Pages",
      "Custom Modern Design",
      "Fully Mobile Responsive",
      "Contact Form Integration",
      "WhatsApp Chat Integration",
      "Google Maps Integration",
      "Social Media Integration",
      "Basic SEO Setup",
      "Fast Loading Website",
      "SSL Security Setup",
      "Google Analytics Integration",
      "1 Year Domain Included",
      "1 Year Hosting Included",
      "1 Revision Round",
      "1 Month Free Support",
      "Delivery in 5–7 Business Days",
    ],
  },

  {
    name: "Growth",
    price: "Starting at $1,499",
    sub: "most popular for growing businesses",
    color: "#8B5CF6",
    popular: true,
    features: [
      "Everything in Launch",
      "Up to 15 Pages",
      "Custom UI/UX Design",
      "Admin Dashboard",
      "Blog Management System",
      "Lead Capture Forms",
      "Email Notifications",
      "Advanced SEO Setup",
      "Google Search Console Setup",
      "Speed Optimization",
      "Image Optimization",
      "Service & Portfolio Management",
      "Testimonials Management",
      "Analytics & Visitor Tracking",
      "1 Year Premium Hosting Included",
      "1 Year Domain Included",
      "3 Revision Rounds",
      "3 Months Free Support",
      "Delivery in 2–3 Weeks",
    ],
  },

  {
    name: "Enterprise",
    price: "Custom Quote",
    sub: "tailored to your requirements",
    color: "#FBBF24",
    popular: false,
    features: [
      "Everything in Growth",
      "Fully Custom Web Application",
      "User Authentication System",
      "Role-Based Access Control",
      "Custom Dashboards",
      "Database Architecture",
      "Payment Gateway Integration",
      "API Integrations",
      "Subscription & Membership System",
      "CRM / ERP Modules",
      "Booking & Scheduling Systems",
      "Advanced Reporting & Analytics",
      "Cloud Deployment",
      "Security Hardening",
      "Performance Optimization",
      "Dedicated Project Manager",
      "Priority Support",
      "1 Year Premium Cloud Hosting Included",
      "Domain Assistance & Setup",
      "Unlimited Revisions During Development",
      "Custom Delivery Timeline",
    ],
  },
];