export const PRICING_INR = [
  {
    name: "Starter",
    price: "₹8,000",
    sub: "per project",
    color: "#10B981",
    popular: false,
    features: [
      "Static Website (5 pages)",
      "Mobile Responsive",
      "WhatsApp Integration",
      "Contact Form",
      "1 Revision Round",
      "7-day delivery",
    ],
  },
  {
    name: "Growth",
    price: "₹20,000",
    sub: "per project",
    color: "#8B5CF6",
    popular: true,
    features: [
      "Dynamic Web App",
      "Admin Dashboard",
      "Payment Integration",
      "Email Notifications",
      "Database Setup",
      "3 Revision Rounds",
      "15-day delivery",
    ],
  },
  {
    name: "Enterprise",
    price: "₹50,000+",
    sub: "custom quote",
    color: "#FBBF24",
    popular: false,
    features: [
      "Full SaaS Product",
      "Custom Features",
      "User Auth + Roles",
      "Subscription System",
      "WhatsApp + Email",
      "Unlimited Revisions",
      "30-day delivery",
    ],
  },
];

export const PRICING_USD = [
  {
    name: "Starter",
    price: "$150",
    sub: "per project",
    color: "#10B981",
    popular: false,
    features: [
      "Static Website (5 pages)",
      "Mobile Responsive",
      "WhatsApp Integration",
      "Contact Form",
      "1 Revision Round",
      "7-day delivery",
    ],
  },
  {
    name: "Growth",
    price: "$350",
    sub: "per project",
    color: "#8B5CF6",
    popular: true,
    features: [
      "Dynamic Web App",
      "Admin Dashboard",
      "Payment Integration",
      "Email Notifications",
      "Database Setup",
      "3 Revision Rounds",
      "15-day delivery",
    ],
  },
  {
    name: "Enterprise",
    price: "$800+",
    sub: "custom quote",
    color: "#FBBF24",
    popular: false,
    features: [
      "Full SaaS Product",
      "Custom Features",
      "User Auth + Roles",
      "Subscription System",
      "WhatsApp + Email",
      "Unlimited Revisions",
      "30-day delivery",
    ],
  },
];
