export const SERVICES = [
  {
    icon: "✦",
    color: "#8B5CF6",
    bg: "rgba(139,92,246,0.12)",
    title: "Web Design",
    desc: "Premium UI/UX design with modern aesthetics that convert visitors into clients.",
    tags: ["Figma", "Responsive", "UI/UX"],
  },
  {
    icon: "⬡",
    color: "#10B981",
    bg: "rgba(16,185,129,0.12)",
    title: "Web Development",
    desc: "Fast, clean, scalable websites built with React and modern tech stack.",
    tags: ["React", "Tailwind", "Performance"],
  },
  {
    icon: "◈",
    color: "#FBBF24",
    bg: "rgba(251,191,36,0.12)",
    title: "Web App Development",
    desc: "Full-stack web applications with powerful backends and smooth frontends.",
    tags: ["Django", "REST API", "PostgreSQL"],
  },
  {
    icon: "◉",
    color: "#EF4444",
    bg: "rgba(239,68,68,0.12)",
    title: "SaaS Development",
    desc: "End-to-end SaaS products with auth, subscriptions, dashboards, and billing.",
    tags: ["SaaS", "Subscriptions", "Dashboard"],
  },
  {
    icon: "⚙",
    color: "#06B6D4",
    bg: "rgba(6,182,212,0.12)",
    title: "Bug Fixing",
    desc: "Quick diagnosis and fixing of frontend/backend bugs in any web project.",
    tags: ["Debug", "Optimize", "Any Stack"],
  },
  {
    icon: "◎",
    color: "#EC4899",
    bg: "rgba(236,72,153,0.12)",
    title: "Payment Integration",
    desc: "Razorpay & Stripe integration for Indian and international clients.",
    tags: ["Razorpay", "Stripe", "Subscriptions"],
  },
];
